server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
polar:
  greeting: Welcome to the local book catalog!

spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000 #timeout on waiting to connect to config server
      request-read-timeout: 5000 #timout on waiting to read config fata from the config server
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  sql:
    init:
      mode: always
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000 #Time to Spend Waiting to geta connection from the Pool
      maximum-pool-size: 5 #Max Number of Connections Kept In the Pool
management:
  endpoints:
    web:
      exposure:
        include: refresh


